# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CloudFlare Plants
email: junade@cloudflare.com
description: > # this means to ignore newlines until "baseurl:"
  CloudFlare's London office has some fine plants. Here we get to learn their names.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ju.je" # the base hostname & protocol for your site
twitter_username: IcyApril
github_username:  IcyApril

# Build settings
markdown: kramdown
